### ISSUE TITLE
missing requirements

### ISSUE THREAD

**Issue by bayesways** [svpino/ml.school#11]
Are the following packages missing from the [requirements.txt](https://github.com/svpino/ml.school/blob/main/requirements.txt) ? I had to install them in order to run [cohort.ipynb](https://github.com/svpino/ml.school/blob/main/program/cohort.ipynb)

- python-dotenv
- ipytest
- boto3
- sagemaker

**Comment by svpino** [comment]
Here is the file right now:

<img width="383" alt="image" src="https://github.com/svpino/ml.school/assets/1126730/2560cf81-e3d8-44c1-b05b-d3c4468687c5">

**Comment by bayesways** [comment]
great
